
name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput


      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
            "env": {
            "DATABASE_URL": "${{ secrets.DATABASE_URL }}"
            }
          }' \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
    
    