name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use the appropriate version for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
      env:
        DATABASE_URL: ${{ EMPRE_RENDER.DATABASE_URL }}  # Ensure this is set in your GitHub Secrets

    - name: Deploy to Render
      run: |
        curl -X POST -H "Authorization: Bearer ${{ EMPRE_RENDER.RENDER_API_KEY }}" \
        "https://api.render.com/v1/services/srv-cs33nvt6l47c73e925s0/deploys"  # Replace with your service ID
